# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-17 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20190516_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_closed',
        ),
    ]
