# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-14 23:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190514_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='color',
            field=models.CharField(blank=True, default='#ffffff', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='notification_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 0, 0, 379359)),
        ),
    ]
